### ISSUE TITLE
Support YAML configuration file

### ISSUE THREAD

**Issue by tperale** [Sprtch/victoria#2]
The configuration should look like something like the following:

```yaml
victoria:
    devices:
        - printer1:
            type: "static"
            address: "192.168.8.8"
            format: "40x60"
            redis: "victoria"
        - printer2:
            type: "static"
            address: "192.168.8.9"
            format: "100x60"
            redis: 
              - victoria
              - victoria2
        - printer3:
            ...
```

Allowing to configure multiple printer that could be connected from ethernet.
